/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wzf_chardev_chardevclass */

#ifndef _Included_com_wzf_chardev_chardevclass
#define _Included_com_wzf_chardev_chardevclass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzf_chardev_chardevclass
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wzf_chardev_chardevclass_read
  (JNIEnv *, jobject);

/*
 * Class:     com_wzf_chardev_chardevclass
 * Method:    write
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wzf_chardev_chardevclass_write
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
